spring.application.name=crud todolist
spring.datasource.url=jdbc:postgresql://localhost:5432/todolist_crud_db
spring.datasource.username=springuser
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true